#!/usr/bin/env python3
"""Fix wrangler.json files generated by Cloudflare adapter for Pages deployment."""
import json, glob, os

for path in glob.glob("dist/**/wrangler.json", recursive=True):
    try:
        with open(path) as fh:
            config = json.load(fh)
        
        # Keep only Pages-compatible fields
        clean = {
            "name": config.get("name", "wedding-platform"),
            "compatibility_date": config.get("compatibility_date", "2026-08-26"),
            "compatibility_flags": config.get("compatibility_flags", ["nodejs_compat"]),
        }
        
        with open(path, "w") as fh:
            json.dump(clean, fh, indent=2)
        print(f"  Fixed: {path}")
    except Exception as e:
        print(f"  Error: {path}: {e}")
